/**
 * The pet animation clips, as the phone build gets them: the HEVC-with-alpha
 * `.mov` only, the one iOS plays. Its sibling petClips.web.ts adds the VP9
 * `.webm` copies for browsers; the bundler picks one file per platform, so
 * the phone never carries the ~76 MB of `.webm` it cannot use.
 *
 * Metro needs every `require` spelled out, so this is a table. Regenerate
 * both files together when a clip is added (keys are "<form>/<clip>").
 */
export interface ClipFiles {
  /** HEVC with alpha: what iOS and Safari play transparent. */
  hevc: number;
  /** VP9 with alpha: what Chrome, Firefox and Edge play transparent. Web builds only. */
  webm?: number;
}

const CLIPS: Record<string, ClipFiles> = {
  'axolotlLifter/cheer': { hevc: require('../../assets/pet/video/axolotlLifter/cheer.mov') },
  'axolotlLifter/collapse': { hevc: require('../../assets/pet/video/axolotlLifter/collapse.mov') },
  'axolotlLifter/dizzy': { hevc: require('../../assets/pet/video/axolotlLifter/dizzy.mov') },
  'axolotlLifter/idle-flex': { hevc: require('../../assets/pet/video/axolotlLifter/idle-flex.mov') },
  'axolotlLifter/lie': { hevc: require('../../assets/pet/video/axolotlLifter/lie.mov') },
  'axolotlLifter/run': { hevc: require('../../assets/pet/video/axolotlLifter/run.mov') },
  'axolotlLifter/sad': { hevc: require('../../assets/pet/video/axolotlLifter/sad.mov') },
  'axolotlRunner/cheer': { hevc: require('../../assets/pet/video/axolotlRunner/cheer.mov') },
  'axolotlRunner/dizzy': { hevc: require('../../assets/pet/video/axolotlRunner/dizzy.mov') },
  'axolotlRunner/idle': { hevc: require('../../assets/pet/video/axolotlRunner/idle.mov') },
  'axolotlRunner/lie': { hevc: require('../../assets/pet/video/axolotlRunner/lie.mov') },
  'axolotlRunner/lie-down': { hevc: require('../../assets/pet/video/axolotlRunner/lie-down.mov') },
  'axolotlRunner/run': { hevc: require('../../assets/pet/video/axolotlRunner/run.mov') },
  'axolotlRunner/tired': { hevc: require('../../assets/pet/video/axolotlRunner/tired.mov') },
  'axolotlScholar/cheer': { hevc: require('../../assets/pet/video/axolotlScholar/cheer.mov') },
  'axolotlScholar/collapse': { hevc: require('../../assets/pet/video/axolotlScholar/collapse.mov') },
  'axolotlScholar/cry': { hevc: require('../../assets/pet/video/axolotlScholar/cry.mov') },
  'axolotlScholar/dizzy': { hevc: require('../../assets/pet/video/axolotlScholar/dizzy.mov') },
  'axolotlScholar/idle': { hevc: require('../../assets/pet/video/axolotlScholar/idle.mov') },
  'axolotlScholar/lie': { hevc: require('../../assets/pet/video/axolotlScholar/lie.mov') },
  'axolotlScholar/walk': { hevc: require('../../assets/pet/video/axolotlScholar/walk.mov') },
  'bearLifter/cheer': { hevc: require('../../assets/pet/video/bearLifter/cheer.mov') },
  'bearLifter/collapse': { hevc: require('../../assets/pet/video/bearLifter/collapse.mov') },
  'bearLifter/dizzy': { hevc: require('../../assets/pet/video/bearLifter/dizzy.mov') },
  'bearLifter/idle-flex': { hevc: require('../../assets/pet/video/bearLifter/idle-flex.mov') },
  'bearLifter/lie': { hevc: require('../../assets/pet/video/bearLifter/lie.mov') },
  'bearLifter/run': { hevc: require('../../assets/pet/video/bearLifter/run.mov') },
  'bearLifter/sad': { hevc: require('../../assets/pet/video/bearLifter/sad.mov') },
  'bearRunner/cheer': { hevc: require('../../assets/pet/video/bearRunner/cheer.mov') },
  'bearRunner/dizzy': { hevc: require('../../assets/pet/video/bearRunner/dizzy.mov') },
  'bearRunner/idle': { hevc: require('../../assets/pet/video/bearRunner/idle.mov') },
  'bearRunner/lie-down': { hevc: require('../../assets/pet/video/bearRunner/lie-down.mov') },
  'bearRunner/run': { hevc: require('../../assets/pet/video/bearRunner/run.mov') },
  'bearRunner/tired': { hevc: require('../../assets/pet/video/bearRunner/tired.mov') },
  'bearScholar/cheer': { hevc: require('../../assets/pet/video/bearScholar/cheer.mov') },
  'bearScholar/collapse': { hevc: require('../../assets/pet/video/bearScholar/collapse.mov') },
  'bearScholar/cry': { hevc: require('../../assets/pet/video/bearScholar/cry.mov') },
  'bearScholar/dizzy': { hevc: require('../../assets/pet/video/bearScholar/dizzy.mov') },
  'bearScholar/idle': { hevc: require('../../assets/pet/video/bearScholar/idle.mov') },
  'bearScholar/walk': { hevc: require('../../assets/pet/video/bearScholar/walk.mov') },
  'bichonLifter/dizzy': { hevc: require('../../assets/pet/video/bichonLifter/dizzy.mov') },
  'bichonLifter/hurt': { hevc: require('../../assets/pet/video/bichonLifter/hurt.mov') },
  'bichonLifter/idle': { hevc: require('../../assets/pet/video/bichonLifter/idle.mov') },
  'bichonLifter/idle-flex': { hevc: require('../../assets/pet/video/bichonLifter/idle-flex.mov') },
  'bichonLifter/jump': { hevc: require('../../assets/pet/video/bichonLifter/jump.mov') },
  'bichonLifter/walk': { hevc: require('../../assets/pet/video/bichonLifter/walk.mov') },
  'bichonRunner/cheer': { hevc: require('../../assets/pet/video/bichonRunner/cheer.mov') },
  'bichonRunner/dizzy': { hevc: require('../../assets/pet/video/bichonRunner/dizzy.mov') },
  'bichonRunner/idle': { hevc: require('../../assets/pet/video/bichonRunner/idle.mov') },
  'bichonRunner/lie': { hevc: require('../../assets/pet/video/bichonRunner/lie.mov') },
  'bichonRunner/lie-down': { hevc: require('../../assets/pet/video/bichonRunner/lie-down.mov') },
  'bichonRunner/run': { hevc: require('../../assets/pet/video/bichonRunner/run.mov') },
  'bichonRunner/tired': { hevc: require('../../assets/pet/video/bichonRunner/tired.mov') },
  'bunnyLifter/cheer': { hevc: require('../../assets/pet/video/bunnyLifter/cheer.mov') },
  'bunnyLifter/collapse': { hevc: require('../../assets/pet/video/bunnyLifter/collapse.mov') },
  'bunnyLifter/dizzy': { hevc: require('../../assets/pet/video/bunnyLifter/dizzy.mov') },
  'bunnyLifter/idle-flex': { hevc: require('../../assets/pet/video/bunnyLifter/idle-flex.mov') },
  'bunnyLifter/lie': { hevc: require('../../assets/pet/video/bunnyLifter/lie.mov') },
  'bunnyLifter/run': { hevc: require('../../assets/pet/video/bunnyLifter/run.mov') },
  'bunnyLifter/sad': { hevc: require('../../assets/pet/video/bunnyLifter/sad.mov') },
  'bunnyRunner/cheer': { hevc: require('../../assets/pet/video/bunnyRunner/cheer.mov') },
  'bunnyRunner/dizzy': { hevc: require('../../assets/pet/video/bunnyRunner/dizzy.mov') },
  'bunnyRunner/idle': { hevc: require('../../assets/pet/video/bunnyRunner/idle.mov') },
  'bunnyRunner/lie-down': { hevc: require('../../assets/pet/video/bunnyRunner/lie-down.mov') },
  'bunnyRunner/run': { hevc: require('../../assets/pet/video/bunnyRunner/run.mov') },
  'bunnyRunner/tired': { hevc: require('../../assets/pet/video/bunnyRunner/tired.mov') },
  'bunnyScholar/cheer': { hevc: require('../../assets/pet/video/bunnyScholar/cheer.mov') },
  'bunnyScholar/collapse': { hevc: require('../../assets/pet/video/bunnyScholar/collapse.mov') },
  'bunnyScholar/cry': { hevc: require('../../assets/pet/video/bunnyScholar/cry.mov') },
  'bunnyScholar/dizzy': { hevc: require('../../assets/pet/video/bunnyScholar/dizzy.mov') },
  'bunnyScholar/idle': { hevc: require('../../assets/pet/video/bunnyScholar/idle.mov') },
  'bunnyScholar/walk': { hevc: require('../../assets/pet/video/bunnyScholar/walk.mov') },
  'dinoLifter/celebrating': { hevc: require('../../assets/pet/video/dinoLifter/celebrating.mov') },
  'dinoLifter/dizzy': { hevc: require('../../assets/pet/video/dinoLifter/dizzy.mov') },
  'dinoLifter/dying': { hevc: require('../../assets/pet/video/dinoLifter/dying.mov') },
  'dinoLifter/idle-flex': { hevc: require('../../assets/pet/video/dinoLifter/idle-flex.mov') },
  'dinoLifter/lie': { hevc: require('../../assets/pet/video/dinoLifter/lie.mov') },
  'dinoLifter/run': { hevc: require('../../assets/pet/video/dinoLifter/run.mov') },
  'dinoLifter/sad': { hevc: require('../../assets/pet/video/dinoLifter/sad.mov') },
  'dinoRunner/celebrating': { hevc: require('../../assets/pet/video/dinoRunner/celebrating.mov') },
  'dinoRunner/dizzy': { hevc: require('../../assets/pet/video/dinoRunner/dizzy.mov') },
  'dinoRunner/dying': { hevc: require('../../assets/pet/video/dinoRunner/dying.mov') },
  'dinoRunner/idle': { hevc: require('../../assets/pet/video/dinoRunner/idle.mov') },
  'dinoRunner/lie': { hevc: require('../../assets/pet/video/dinoRunner/lie.mov') },
  'dinoRunner/run': { hevc: require('../../assets/pet/video/dinoRunner/run.mov') },
  'dinoRunner/sad': { hevc: require('../../assets/pet/video/dinoRunner/sad.mov') },
  'dinoScholar/celebrating': { hevc: require('../../assets/pet/video/dinoScholar/celebrating.mov') },
  'dinoScholar/dizzy': { hevc: require('../../assets/pet/video/dinoScholar/dizzy.mov') },
  'dinoScholar/dying': { hevc: require('../../assets/pet/video/dinoScholar/dying.mov') },
  'dinoScholar/idle': { hevc: require('../../assets/pet/video/dinoScholar/idle.mov') },
  'dinoScholar/lie': { hevc: require('../../assets/pet/video/dinoScholar/lie.mov') },
  'dinoScholar/run': { hevc: require('../../assets/pet/video/dinoScholar/run.mov') },
  'dinoScholar/sad': { hevc: require('../../assets/pet/video/dinoScholar/sad.mov') },
  'foxLifter/celebrating': { hevc: require('../../assets/pet/video/foxLifter/celebrating.mov') },
  'foxLifter/dizzy': { hevc: require('../../assets/pet/video/foxLifter/dizzy.mov') },
  'foxLifter/dying': { hevc: require('../../assets/pet/video/foxLifter/dying.mov') },
  'foxLifter/idle-flex': { hevc: require('../../assets/pet/video/foxLifter/idle-flex.mov') },
  'foxLifter/lie': { hevc: require('../../assets/pet/video/foxLifter/lie.mov') },
  'foxLifter/run': { hevc: require('../../assets/pet/video/foxLifter/run.mov') },
  'foxLifter/sad': { hevc: require('../../assets/pet/video/foxLifter/sad.mov') },
  'foxRunner/celebrating': { hevc: require('../../assets/pet/video/foxRunner/celebrating.mov') },
  'foxRunner/dizzy': { hevc: require('../../assets/pet/video/foxRunner/dizzy.mov') },
  'foxRunner/dying': { hevc: require('../../assets/pet/video/foxRunner/dying.mov') },
  'foxRunner/idle': { hevc: require('../../assets/pet/video/foxRunner/idle.mov') },
  'foxRunner/lie': { hevc: require('../../assets/pet/video/foxRunner/lie.mov') },
  'foxRunner/run': { hevc: require('../../assets/pet/video/foxRunner/run.mov') },
  'foxRunner/sad': { hevc: require('../../assets/pet/video/foxRunner/sad.mov') },
  'foxScholar/celebrating': { hevc: require('../../assets/pet/video/foxScholar/celebrating.mov') },
  'foxScholar/dizzy': { hevc: require('../../assets/pet/video/foxScholar/dizzy.mov') },
  'foxScholar/dying': { hevc: require('../../assets/pet/video/foxScholar/dying.mov') },
  'foxScholar/idle': { hevc: require('../../assets/pet/video/foxScholar/idle.mov') },
  'foxScholar/lie': { hevc: require('../../assets/pet/video/foxScholar/lie.mov') },
  'foxScholar/run': { hevc: require('../../assets/pet/video/foxScholar/run.mov') },
  'foxScholar/sad': { hevc: require('../../assets/pet/video/foxScholar/sad.mov') },
  'koalaLifter/celebrating': { hevc: require('../../assets/pet/video/koalaLifter/celebrating.mov') },
  'koalaLifter/dizzy': { hevc: require('../../assets/pet/video/koalaLifter/dizzy.mov') },
  'koalaLifter/dying': { hevc: require('../../assets/pet/video/koalaLifter/dying.mov') },
  'koalaLifter/idle-flex': { hevc: require('../../assets/pet/video/koalaLifter/idle-flex.mov') },
  'koalaLifter/lie': { hevc: require('../../assets/pet/video/koalaLifter/lie.mov') },
  'koalaLifter/run': { hevc: require('../../assets/pet/video/koalaLifter/run.mov') },
  'koalaLifter/sad': { hevc: require('../../assets/pet/video/koalaLifter/sad.mov') },
  'koalaRunner/celebrating': { hevc: require('../../assets/pet/video/koalaRunner/celebrating.mov') },
  'koalaRunner/dizzy': { hevc: require('../../assets/pet/video/koalaRunner/dizzy.mov') },
  'koalaRunner/dying': { hevc: require('../../assets/pet/video/koalaRunner/dying.mov') },
  'koalaRunner/idle': { hevc: require('../../assets/pet/video/koalaRunner/idle.mov') },
  'koalaRunner/lie': { hevc: require('../../assets/pet/video/koalaRunner/lie.mov') },
  'koalaRunner/run': { hevc: require('../../assets/pet/video/koalaRunner/run.mov') },
  'koalaRunner/sad': { hevc: require('../../assets/pet/video/koalaRunner/sad.mov') },
  'koalaScholar/celebrating': { hevc: require('../../assets/pet/video/koalaScholar/celebrating.mov') },
  'koalaScholar/dizzy': { hevc: require('../../assets/pet/video/koalaScholar/dizzy.mov') },
  'koalaScholar/dying': { hevc: require('../../assets/pet/video/koalaScholar/dying.mov') },
  'koalaScholar/idle': { hevc: require('../../assets/pet/video/koalaScholar/idle.mov') },
  'koalaScholar/lie': { hevc: require('../../assets/pet/video/koalaScholar/lie.mov') },
  'koalaScholar/run': { hevc: require('../../assets/pet/video/koalaScholar/run.mov') },
  'koalaScholar/sad': { hevc: require('../../assets/pet/video/koalaScholar/sad.mov') },
  'otter/cheer': { hevc: require('../../assets/pet/video/otter/cheer.mov') },
  'otter/collapse': { hevc: require('../../assets/pet/video/otter/collapse.mov') },
  'otter/cry': { hevc: require('../../assets/pet/video/otter/cry.mov') },
  'otter/dizzy': { hevc: require('../../assets/pet/video/otter/dizzy.mov') },
  'otter/idle': { hevc: require('../../assets/pet/video/otter/idle.mov') },
  'otter/lie': { hevc: require('../../assets/pet/video/otter/lie.mov') },
  'otter/run': { hevc: require('../../assets/pet/video/otter/run.mov') },
  'otterLifter/celebrating': { hevc: require('../../assets/pet/video/otterLifter/celebrating.mov') },
  'otterLifter/dizzy': { hevc: require('../../assets/pet/video/otterLifter/dizzy.mov') },
  'otterLifter/dying': { hevc: require('../../assets/pet/video/otterLifter/dying.mov') },
  'otterLifter/idle-flex': { hevc: require('../../assets/pet/video/otterLifter/idle-flex.mov') },
  'otterLifter/lie': { hevc: require('../../assets/pet/video/otterLifter/lie.mov') },
  'otterLifter/run': { hevc: require('../../assets/pet/video/otterLifter/run.mov') },
  'otterLifter/sad': { hevc: require('../../assets/pet/video/otterLifter/sad.mov') },
  'otterRunner/celebrating': { hevc: require('../../assets/pet/video/otterRunner/celebrating.mov') },
  'otterRunner/dizzy': { hevc: require('../../assets/pet/video/otterRunner/dizzy.mov') },
  'otterRunner/dying': { hevc: require('../../assets/pet/video/otterRunner/dying.mov') },
  'otterRunner/idle': { hevc: require('../../assets/pet/video/otterRunner/idle.mov') },
  'otterRunner/lie': { hevc: require('../../assets/pet/video/otterRunner/lie.mov') },
  'otterRunner/run': { hevc: require('../../assets/pet/video/otterRunner/run.mov') },
  'otterRunner/sad': { hevc: require('../../assets/pet/video/otterRunner/sad.mov') },
  'otterScholar/celebrating': { hevc: require('../../assets/pet/video/otterScholar/celebrating.mov') },
  'otterScholar/dizzy': { hevc: require('../../assets/pet/video/otterScholar/dizzy.mov') },
  'otterScholar/dying': { hevc: require('../../assets/pet/video/otterScholar/dying.mov') },
  'otterScholar/idle': { hevc: require('../../assets/pet/video/otterScholar/idle.mov') },
  'otterScholar/lie': { hevc: require('../../assets/pet/video/otterScholar/lie.mov') },
  'otterScholar/run': { hevc: require('../../assets/pet/video/otterScholar/run.mov') },
  'otterScholar/sad': { hevc: require('../../assets/pet/video/otterScholar/sad.mov') },
  'shibaRunner/cheer': { hevc: require('../../assets/pet/video/shibaRunner/cheer.mov') },
  'shibaRunner/dizzy': { hevc: require('../../assets/pet/video/shibaRunner/dizzy.mov') },
  'shibaRunner/idle': { hevc: require('../../assets/pet/video/shibaRunner/idle.mov') },
  'shibaRunner/lie': { hevc: require('../../assets/pet/video/shibaRunner/lie.mov') },
  'shibaRunner/lie-down': { hevc: require('../../assets/pet/video/shibaRunner/lie-down.mov') },
  'shibaRunner/run': { hevc: require('../../assets/pet/video/shibaRunner/run.mov') },
  'shibaRunner/tired': { hevc: require('../../assets/pet/video/shibaRunner/tired.mov') },
  'tabbyCatLifter/celebrating': { hevc: require('../../assets/pet/video/tabbyCatLifter/celebrating.mov') },
  'tabbyCatLifter/dizzy': { hevc: require('../../assets/pet/video/tabbyCatLifter/dizzy.mov') },
  'tabbyCatLifter/dying': { hevc: require('../../assets/pet/video/tabbyCatLifter/dying.mov') },
  'tabbyCatLifter/idle-flex': { hevc: require('../../assets/pet/video/tabbyCatLifter/idle-flex.mov') },
  'tabbyCatLifter/lie': { hevc: require('../../assets/pet/video/tabbyCatLifter/lie.mov') },
  'tabbyCatLifter/run': { hevc: require('../../assets/pet/video/tabbyCatLifter/run.mov') },
  'tabbyCatLifter/sad': { hevc: require('../../assets/pet/video/tabbyCatLifter/sad.mov') },
  'tabbyCatRunner/celebrating': { hevc: require('../../assets/pet/video/tabbyCatRunner/celebrating.mov') },
  'tabbyCatRunner/dizzy': { hevc: require('../../assets/pet/video/tabbyCatRunner/dizzy.mov') },
  'tabbyCatRunner/dying': { hevc: require('../../assets/pet/video/tabbyCatRunner/dying.mov') },
  'tabbyCatRunner/idle': { hevc: require('../../assets/pet/video/tabbyCatRunner/idle.mov') },
  'tabbyCatRunner/lie': { hevc: require('../../assets/pet/video/tabbyCatRunner/lie.mov') },
  'tabbyCatRunner/run': { hevc: require('../../assets/pet/video/tabbyCatRunner/run.mov') },
  'tabbyCatRunner/sad': { hevc: require('../../assets/pet/video/tabbyCatRunner/sad.mov') },
  'tabbyCatScholar/celebrating': { hevc: require('../../assets/pet/video/tabbyCatScholar/celebrating.mov') },
  'tabbyCatScholar/dizzy': { hevc: require('../../assets/pet/video/tabbyCatScholar/dizzy.mov') },
  'tabbyCatScholar/dying': { hevc: require('../../assets/pet/video/tabbyCatScholar/dying.mov') },
  'tabbyCatScholar/idle': { hevc: require('../../assets/pet/video/tabbyCatScholar/idle.mov') },
  'tabbyCatScholar/lie': { hevc: require('../../assets/pet/video/tabbyCatScholar/lie.mov') },
  'tabbyCatScholar/run': { hevc: require('../../assets/pet/video/tabbyCatScholar/run.mov') },
  'tabbyCatScholar/sad': { hevc: require('../../assets/pet/video/tabbyCatScholar/sad.mov') },
};

export const clipFiles = (key: string): ClipFiles => {
  const files = CLIPS[key];
  if (!files) throw new Error(`No pet clip "${key}"`);
  return files;
};
